name: test
description: A test app for Security Check!
version: 1.0.0
publish_to: none
homepage: https://github.com/iamtheblackunicorn/securitycheck
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  securitycheck:
    git: git://github.com/iamtheblackunicorn/securitycheck.git
