name: securitycheck
description: A library to check whether your passwords are secure and strong.
version: 1.1.0
homepage: https://github.com/iamtheblackunicorn/securitycheck
environment:
  sdk: '>=2.12.0 <3.0.0'
dev_dependencies:
  pedantic: ^1.11.0
